### PR TITLE
Several commits converged in this Pull request

### PR DESCRIPTION
**Pull request by campfire29**
Update to the Report Production Section: The first two paragraphs were updated with additional text (some from other volumes for consistency). I integrated the existing text into the new first paragraph. The "TBD" and the paragraph following the "TBD" were left as-is.

The second commit in this pull request is for updates to Section 1.1 only.

### CODE REVIEW

**Comment by campfire29** [comment]
My apologies. It looks like I added two commits to this pull request. I intended to make them separate pull requests to make your review easier. Please let me know if this causes issues and I can redo them.

**Comment by campfire29** [comment]
Please take note of the removal of the Contribution appendix. Please give me a call if you have any questions about the reasoning. Thanks.

**Comment by laszewsk** [comment]
you are makeing too many changes in one pull request, naturally i have to preserve the contribution section somewhere else so i remember how to do it, deleting will just lead to losing the information and me having to reinvent it. I think in these cases it would be better to just put a TODO in there or file an issue

**Review by laszewsk — CHANGES_REQUESTED** [review]
THis pull request contains several important sections that are suggested to be removed. Others add information. Thus we can not approve this pull request. It is therefore rejected and has to be done with individual pull requests

**Comment by laszewsk** [comment]
THis pull request contains several important sections that are suggested to be removed. Others add information. Thus we can not approve this pull request. It is therefore rejected and has to be done with individual pull requests

**Pull request closed without merging**
