### PR TITLE
Conflict: Delete Report Production text

### PR DESCRIPTION
**Pull request by campfire29**
The text in the Report Production section was from Volume 9. It was deleted.

### CODE REVIEW

**Review by laszewsk — CHANGES_REQUESTED** [review]
due to conflicts rejected. However I approved another pull reqest that did a similar change. Veryfy  If this one is needed and close this

**Comment by campfire29** [comment]
I'm not 100% sure where the conflict is but I see that the new report production text has been added. The text in this deletion (I think) is the text below. Some is from Volume 9 which was deleted and the rest was incorporated into the new text that was accepted into the Report Production section. Please let me know if I need to create a new pull request for this deletion. The text that should be deleted form the Report Production section is the following:

-NBDIF: Volume 8, Interfaces is one of nine volumes, whose overall aims
-are to define and specify interfaces to implement the Big Data
-Reference Architecture.
 
-173 The NBDIF: Volume 8, interafces from discussions during the weekly
-NBD-PWG 174 conference calls. Topics included in this volume began to
-take form in Phase 2 of the NBD-PWG work and this 175 volume
-represents the groundwork for additional content planned for Phase 3.
-
-176 During the discussions, the NBD-PWG identified the need to specify
-a variety of interfaces including:
 
 TBD 
 
 
-include the list here. The Standards Roadmap Subgroup will continue to
-develop these and possibly other topics during Phase 3. The current
-version reflects the breadth of knowledge of the Subgroup members. The
-public’s participation in Phase 3 of the NBD-PWG work is encouraged.
-To achieve technical and high quality document content, this document
-will go through public comments period along with NIST internal
-review.

**Comment by campfire29** [comment]
Please give me a call if I need to do anything with this pull request. I am unsure about the workflow here. The text in my previous comment shouldn't be in the document. The new text that was incorporated should replace it. Thanks.

**Comment by laszewsk** [comment]
will be revisited

**Pull request closed without merging**
